import { z } from "zod";

export const insertUserSchema = z.object({
  email: z.string().email().optional(),
  password: z.string().optional(),
  firstName: z.string().optional(),
  lastName: z.string().optional(),
  profileImageUrl: z.string().optional(),
  role: z.string().optional(),
  age: z.number().optional(),
  dateOfBirth: z.string().optional(),
  gender: z.string().optional(),
  phone: z.string().optional(),
  bio: z.string().optional(),
  cvUrl: z.string().optional(),
  location: z.string().optional(),
  state: z.string().optional(),
  lga: z.string().optional(),
  city: z.string().optional(),
  expectedSalaryMin: z.number().optional(),
  expectedSalaryMax: z.number().optional(),
  companyName: z.string().optional(),
  businessCategory: z.string().optional(),
  companyLogo: z.string().optional(),
  companyAddress: z.string().optional(),
  companyCity: z.string().optional(),
  companyState: z.string().optional(),
  isRegisteredCompany: z.boolean().optional(),
  companyRegNo: z.string().optional(),
  subscribedToNewsletter: z.boolean().optional(),
});

export const insertJobSchema = z.object({
  employerId: z.string(),
  title: z.string(),
  description: z.string(),
  category: z.string(),
  jobType: z.string(),
  salaryMin: z.number(),
  salaryMax: z.number(),
  wage: z.string(),
  location: z.string(),
  state: z.string().optional(),
  lga: z.string().optional(),
  requirements: z.string().optional(),
  benefits: z.string().optional(),
  deadline: z.union([z.string(), z.date(), z.null()]).optional(),
  status: z.string().optional(),
  tags: z.array(z.string()).optional(),
  isFeatured: z.boolean().optional(),
});

export const insertApplicationSchema = z.object({
  jobId: z.number(),
  applicantId: z.string(),
  coverLetter: z.string().optional(),
  cvUrl: z.string().optional(),
  notes: z.string().optional(),
});
