export type JobSector = {
  name: string;
  subcategories: string[];
};

export const jobSectors: JobSector[] = [
  {
    name: "Admin & Office",
    subcategories: [
      "Administrative Officer",
      "Data Entry Clerk",
      "Executive Assistant",
      "Front Desk / Receptionist",
      "Office Assistant",
      "Office Manager",
      "Personal Assistant",
      "Records / Filing Clerk",
      "Secretary",
      "Virtual Assistant",
    ],
  },
  {
    name: "Agriculture",
    subcategories: [
      "Agricultural Extension Officer",
      "Agronomist",
      "Farm Manager",
      "Farm Worker",
      "Fishery Officer",
      "Livestock / Poultry Attendant",
      "Veterinary Assistant",
    ],
  },
  {
    name: "Banking, Finance & Insurance",
    subcategories: [
      "Accountant",
      "Auditor",
      "Bank Teller",
      "Bookkeeper",
      "Credit Analyst",
      "Financial Adviser",
      "Financial Analyst",
      "Insurance Agent",
      "Investment Analyst",
      "Payroll Specialist",
      "Tax Consultant",
    ],
  },
  {
    name: "Construction & Real Estate",
    subcategories: [
      "Architect",
      "CAD Technician",
      "Civil Engineer",
      "Construction Worker",
      "Estate Agent / Valuer",
      "Facility Manager",
      "Mason / Bricklayer",
      "Project Supervisor (Construction)",
      "Quantity Surveyor",
      "Site Engineer",
      "Surveyor",
    ],
  },
  {
    name: "Customer Service & Support",
    subcategories: [
      "Call Centre Agent",
      "Client Relations Officer",
      "Customer Service Representative",
      "Help Desk Analyst",
      "Tech Support Specialist",
    ],
  },
  {
    name: "Design, Arts & Crafts",
    subcategories: [
      "Fashion Designer",
      "Graphic Designer",
      "Interior Designer",
      "UI/UX Designer",
      "Video Editor / Animator",
    ],
  },
  {
    name: "Domestic & Household",
    subcategories: [
      "Cleaner / Janitor",
      "Cook (Domestic)",
      "Driver (Personal)",
      "Gardener",
      "Housekeeper",
      "Laundry Attendant",
      "Nanny / Caregiver",
    ],
  },
  {
    name: "Education & Training",
    subcategories: [
      "Academic Researcher",
      "Childcare Worker",
      "Corporate Trainer",
      "Lecturer / Professor",
      "School Administrator",
      "Teacher",
      "Tutor",
    ],
  },
  {
    name: "Engineering & Technical",
    subcategories: [
      "Biomedical Engineer",
      "Chemical Engineer",
      "Electrical Engineer",
      "Electronics Technician",
      "Mechanical Engineer",
      "Petroleum Engineer",
      "Production Engineer",
      "Structural Engineer",
      "Telecommunications Engineer",
    ],
  },
  {
    name: "Graduate Trainee & Internship",
    subcategories: [
      "Graduate Trainee",
      "Industrial Trainee (IT / SIWES)",
      "Intern",
      "Management Trainee",
      "National Youth Service (NYSC)",
    ],
  },
  {
    name: "Healthcare & Medical",
    subcategories: [
      "Community Health Worker",
      "Dentist",
      "Healthcare Administrator",
      "Lab Technician",
      "Nurse / Midwife",
      "Optometrist",
      "Pharmacist",
      "Physician / Doctor",
      "Physiotherapist",
      "Public Health Officer",
      "Radiographer",
    ],
  },
  {
    name: "Hospitality & Hotel",
    subcategories: [
      "Barista",
      "Barman / Bartender",
      "Chef / Cook",
      "Concierge",
      "Fast Food Attendant",
      "Hotel Receptionist",
      "Housekeeper / Room Attendant",
      "Kitchen Assistant / Steward",
      "Porter / Luggage Handler",
      "Spa Therapist",
      "Tour & Travel Guide",
      "Waiter / Waitress",
    ],
  },
  {
    name: "Human Resources",
    subcategories: [
      "Compensation & Benefits Analyst",
      "HR Business Partner",
      "HR Generalist",
      "HR Manager",
      "HR Officer",
      "Learning & Development Officer",
      "Recruitment Specialist",
      "Talent Acquisition Manager",
    ],
  },
  {
    name: "IT & Software",
    subcategories: [
      "Cloud Engineer",
      "Cybersecurity Analyst",
      "Data Analyst",
      "Data Scientist",
      "Database Administrator",
      "DevOps Engineer",
      "IT Support Specialist",
      "Mobile App Developer",
      "Network Engineer",
      "QA / Test Engineer",
      "Software Developer",
      "Software Engineer",
      "Systems Administrator",
      "Web Developer",
    ],
  },
  {
    name: "Legal",
    subcategories: [
      "Barrister / Solicitor",
      "Company Secretary",
      "Compliance Officer",
      "Legal Adviser",
      "Legal Officer",
      "Paralegal",
    ],
  },
  {
    name: "Logistics & Supply Chain",
    subcategories: [
      "Dispatch Rider",
      "Driver (Commercial)",
      "Fleet Manager",
      "Inventory Officer",
      "Logistics Coordinator",
      "Procurement Officer",
      "Supply Chain Manager",
      "Warehouse Supervisor",
    ],
  },
  {
    name: "Management & Business Development",
    subcategories: [
      "Account Manager",
      "Branch Manager",
      "Business Analyst",
      "Business Development Manager",
      "General Manager",
      "Managing Director / CEO",
      "Operations Manager",
      "Product Manager",
      "Programme / Project Manager",
      "Strategy Analyst",
    ],
  },
  {
    name: "Manufacturing & Industrial",
    subcategories: [
      "Box Production Worker",
      "Factory Worker / Machine Operator",
      "Maintenance Technician",
      "Plant Manager",
      "Production Supervisor",
      "Quality Control Officer",
      "Safety / HSE Officer",
      "Welder / Fabricator",
    ],
  },
  {
    name: "Marketing & Communications",
    subcategories: [
      "Brand Manager",
      "Content Creator / Writer",
      "Copywriter",
      "Digital Marketing Specialist",
      "Event Planner",
      "Marketing Manager",
      "Public Relations Officer",
      "SEO Specialist",
      "Social Media Manager",
    ],
  },
  {
    name: "Media & Journalism",
    subcategories: [
      "Broadcaster / Presenter",
      "Cameraman / Videographer",
      "Editor (Print / Digital)",
      "Journalist / Reporter",
      "Media Producer",
      "Sound Engineer",
    ],
  },
  {
    name: "NGO & Non-Profit",
    subcategories: [
      "Community Development Officer",
      "Field Officer",
      "Grant Writer",
      "Monitoring & Evaluation Officer",
      "Programme Coordinator",
      "Volunteer Coordinator",
    ],
  },
  {
    name: "Oil & Gas / Energy",
    subcategories: [
      "Drilling Engineer",
      "Electrical Technician (Energy)",
      "HSE Manager",
      "Petroleum Geologist",
      "Pipeline Engineer",
      "Power Plant Operator",
      "Renewable Energy Technician",
      "Rig Worker",
    ],
  },
  {
    name: "Research & Strategy",
    subcategories: [
      "Data Researcher",
      "Market Research Analyst",
      "Policy Analyst",
      "Research Associate",
      "Strategy Consultant",
    ],
  },
  {
    name: "Retail & Sales",
    subcategories: [
      "Account Executive",
      "B2B Sales Executive",
      "Cashier",
      "Merchandiser",
      "Sales Assistant / Attendant",
      "Sales Development Rep (SDR)",
      "Sales Manager",
      "Sales Representative",
      "Store Keeper",
      "Tele-Sales Agent",
    ],
  },
  {
    name: "Security & Safety",
    subcategories: [
      "CCTV / Surveillance Operator",
      "Fire Safety Officer",
      "Safety Officer",
      "Security Guard",
      "Security Supervisor",
    ],
  },
  {
    name: "Telecommunications",
    subcategories: [
      "Base Station Engineer",
      "Field Technician (Telecom)",
      "Network Planner",
      "RF Engineer",
      "Telecom Sales Executive",
    ],
  },
  {
    name: "Trades & Maintenance",
    subcategories: [
      "AC / Refrigeration Technician",
      "Auto Mechanic",
      "Carpenter",
      "Electrician",
      "Generator Technician",
      "HVAC Technician",
      "Painter",
      "Photographer",
      "Plumber",
      "Repair Technician",
      "Stylist (Barbing)",
      "Stylist (Fashion)",
      "Stylist (Ladies)",
      "Stylist (Spa / Beauty)",
      "Stylist (Unisex)",
      "Tailor / Seamstress",
      "Tiler",
    ],
  },
  {
    name: "Transport & Aviation",
    subcategories: [
      "Airline Ground Staff",
      "Bus / Taxi Driver",
      "Flight Attendant",
      "Pilot",
      "Shipping / Clearing Agent",
      "Transport Coordinator",
    ],
  },
  {
    name: "Other",
    subcategories: [
      "Other",
    ],
  },
];

export const allJobCategories: string[] = jobSectors.flatMap(s => s.subcategories);

export const allSectorNames: string[] = jobSectors.map(s => s.name);

export function getSectorForCategory(category: string): string | undefined {
  return jobSectors.find(s => s.subcategories.includes(category))?.name;
}

export function getSubcategoriesForSector(sectorName: string): string[] {
  return jobSectors.find(s => s.name === sectorName)?.subcategories || [];
}

export const businessCategories = [
  "Admin & Office",
  "Agriculture",
  "Banking, Finance & Insurance",
  "Cleaning & Maintenance",
  "Construction & Real Estate",
  "Consulting & Professional Services",
  "Design, Arts & Crafts",
  "Domestic & Household",
  "Education & Training",
  "Engineering & Technical",
  "Event Management",
  "Government & Public Service",
  "Healthcare & Medical",
  "Hospitality & Hotel",
  "Human Resources",
  "IT & Software",
  "Legal",
  "Logistics & Supply Chain",
  "Management & Business Development",
  "Manufacturing & Industrial",
  "Marketing & Communications",
  "Media & Journalism",
  "NGO & Non-Profit",
  "Oil & Gas / Energy",
  "Research & Strategy",
  "Restaurant & Food Service",
  "Retail & Sales",
  "Security & Safety",
  "Telecommunications",
  "Transport & Aviation",
  "Other",
];
